matrix:
    include:
        - language: node_js
          node_js:
            - lts/*
          script:
              - yarn build:node
          cache:
            yarn: true
            directories:
              - 'node_modules'

          deploy:
            provider: script
            skip_cleanup: true
            script: 
              - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/admin/dist/ btsnake@185.26.156.85:etc/lindy-website/admin/
              - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/assets/ btsnake@185.26.156.85:etc/lindy-website/

            on:
              branch: deploy

        - language: rust
          rust:
              - nightly
          script:
              - cargo build --release
          cache: cargo

          deploy:
            provider: script
            skip_cleanup: true
            script: 
              - ssh btsnake@185.26.156.85 supervisorctl stop lindy-website
              - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target/release/lindyhop-aachen btsnake@185.26.156.85:bin/lindy-website
              - ssh btsnake@185.26.156.85 supervisorctl start lindy-website
            on:
              branch: deploy

install: yarn --frozen-lockfile

addons:
  ssh_known_hosts:
  - 185.26.156.85

before_install:
- openssl aes-256-cbc -K $encrypted_c628346eb8fe_key -iv $encrypted_c628346eb8fe_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
