matrix:
    include:
        - language: node_js
          node_js:
            - lts/*
          script:
              - yarn build:node
          cache:
            yarn: true
            directories:
              - 'node_modules'

        - language: rust
          rust:
              - nightly
          script:
              - cargo build --verbose --all
          cache: cargo

install: yarn --frozen-lockfile

before_install:
- openssl aes-256-cbc -K $encrypted_c628346eb8fe_key -iv $encrypted_c628346eb8fe_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target/release/lindyhop-aachen btsnake@185.26.156.85:bin/
  on:
    branch: deploy
