language: node_js
node_js:
  - "lts/*"

# Prevent automatically created tags from retriggering the build.
# See https://docs.travis-ci.com/user/deployment/releases/#when-tag-is-not-set-at-deployment-time
branches:
  except:
   - /^untagged/
