language: node_js
node_js:
  - "lts/*"

# Do not run when triggered by tag.
# See https://github.com/travis-ci/travis-ci/issues/8051#issuecomment-335517982
if: tag is blank

services:
  - docker

jobs:
  include:
    - stage: test
      script: yarn test
      
    - stage: build
      script:
        - docker build -t lindy .
      before_deploy:
        # Copy built files out of container
        - docker create --name lindy lindy
        - "docker cp lindy:/lindyhop-aachen ./dist"
        # Prepare for upload
        - cd dist; zip ../dist.zip *; cd ..
        # Tag for GitHub Releases
        - git config --local user.name "Travis CI"
        - git config --local user.email "Travis CI"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%dT%H-%M-%S')}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
        file: dist.zip
        on:
          branch:
            - deploy-docker
