language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_c628346eb8fe_key -iv $encrypted_c628346eb8fe_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
