language: node_js
node_js:
  - "lts/*"

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - skip
      before_deploy:
        # Copy built files out of container
        - mkdir ./dist
        - touch ./dist/test
        # Prepare for upload
        - zip dist.zip ./dist/**/*
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
        file: dist.zip
