FROM rust:latest

WORKDIR rust

RUN rustup toolchain install nightly --component rustfmt
RUN rustup override set nightly
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./src ./src
COPY ./migrations ./migrations
COPY ./Rocket.toml ./Rocket.toml

CMD cargo fmt -- --check && cargo test