FROM rustlang/rust:nightly

WORKDIR rust

RUN rustup component add rustfmt --toolchain nightly
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./src ./src
COPY ./migrations ./migrations
COPY ./Rocket.toml ./Rocket.toml

CMD cargo fmt -- --check && cargo test